In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("bank.csv", sep=";")

In [3]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   str
 2   marital    4521 non-null   str
 3   education  4521 non-null   str
 4   default    4521 non-null   str
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   str
 7   loan       4521 non-null   str
 8   contact    4521 non-null   str
 9   day        4521 non-null   int64
 10  month      4521 non-null   str
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   str
 16  y          4521 non-null   str
dtypes: int64(7), str(10)
memory usage: 600.6 KB

In [5]:
df.shape

(4521, 17)

In [6]:
print("Numerical:")
print(df.select_dtypes(include="number").columns.tolist())

Numerical:
['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

In [7]:
print("Categorical:")
print(df.select_dtypes(include=["object", "string"]).columns.tolist())

Categorical:
['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome', 'y']

In [8]:
numerical_cols = [
    "age",
    "balance",
    "day",
    "duration",
    "campaign",
    "pdays",
    "previous"
]

categorical_cols = [
    "job",
    "marital",
    "education",
    "default",
    "housing",
    "loan",
    "contact",
    "month",
    "poutcome"
]

target = "y"

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
counts = df["y"].value_counts()

percentages = df["y"].value_counts(normalize=True) * 100

print(counts)
print(percentages)

y
no     4000
yes     521
Name: count, dtype: int64
y
no     88.476001
yes    11.523999
Name: proportion, dtype: float64

In [11]:
df[numerical_cols].describe()

,age,balance,day,duration,campaign,pdays,previous
count,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000,4521.000000
mean,41.170095,1422.657819,15.915284,263.961292,2.793630,39.766645,0.542579
std,10.576211,3009.638142,8.247667,259.856633,3.109807,100.121124,1.693562
min,19.000000,-3313.000000,1.000000,4.000000,1.000000,-1.000000,0.000000
25%,33.000000,69.000000,9.000000,104.000000,1.000000,-1.000000,0.000000
50%,39.000000,444.000000,16.000000,185.000000,2.000000,-1.000000,0.000000
75%,49.000000,1480.000000,21.000000,329.000000,3.000000,-1.000000,0.000000
max,87.000000,71188.000000,31.000000,3025.000000,50.000000,871.000000,25.000000

In [12]:
df["balance"].sort_values(ascending=False).head(10)

3700    71188
2989    42045
1483    27733
1881    27359
3830    27069
871     26965
4047    26452
3011    26394
2196    26306
1031    25824
Name: balance, dtype: int64

In [13]:
Q1 = df["balance"].quantile(0.25)
Q3 = df["balance"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
print(Q1, Q3)
print(lower, upper)

69.0 1480.0
-2047.5 3596.5

In [14]:
df[df["balance"] > upper]["balance"].count()

np.int64(504)

In [15]:
df[df["balance"] > upper]["y"].value_counts(normalize=True) * 100

y
no     85.714286
yes    14.285714
Name: proportion, dtype: float64

In [16]:
df["y"].value_counts(normalize=True) * 100

y
no     88.476001
yes    11.523999
Name: proportion, dtype: float64

In [17]:
df[categorical_cols].nunique()

job          12
marital       3
education     4
default       2
housing       2
loan          2
contact       3
month        12
poutcome      4
dtype: int64

In [18]:
for col in categorical_cols:
    print(f"---{col}---")
    print(df[col].value_counts())

---job---
job
management       969
blue-collar      946
technician       768
admin.           478
services         417
retired          230
self-employed    183
entrepreneur     168
unemployed       128
housemaid        112
student           84
unknown           38
Name: count, dtype: int64
---marital---
marital
married     2797
single      1196
divorced     528
Name: count, dtype: int64
---education---
education
secondary    2306
tertiary     1350
primary       678
unknown       187
Name: count, dtype: int64
---default---
default
no     4445
yes      76
Name: count, dtype: int64
---housing---
housing
yes    2559
no     1962
Name: count, dtype: int64
---loan---
loan
no     3830
yes     691
Name: count, dtype: int64
---contact---
contact
cellular     2896
unknown      1324
telephone     301
Name: count, dtype: int64
---month---
month
may    1398
jul     706
aug     633
jun     531
nov     389
apr     293
feb     222
jan     148
oct      80
sep      52
mar      49
dec      20
Name: count, dtype: int64
---poutcome---
poutcome
unknown    3705
failure     490
other       197
success     129
Name: count, dtype: int64

In [19]:
df.groupby("poutcome")["y"].value_counts(normalize=True) * 100

poutcome  y
failure   no     87.142857
          yes    12.857143
other     no     80.710660
          yes    19.289340
success   yes    64.341085
          no     35.658915
unknown   no     90.904184
          yes     9.095816
Name: proportion, dtype: float64

Target:
    y → imbalanced (~88/12)

Numeric:
    balance → strongly right-skewed, many IQR outliers
    age → mild right-skew
    other numeric features → need preprocessing consideration

Categorical:
    rare categories → default=yes, month=dec, etc.
    unknown categories → contact, poutcome, job, education
    poutcome → potentially strong relationship with target